version: "3.9"

services:
  # solace:
  #   image: solace/solace-pubsub-standard
  #   environment:
  #     - username_admin_globalaccesslevel=admin
  #     - username_admin_password=admin
  #   ports:
  #     - "8081:8080"
  #     - "55555:55555"
  #     - "8008:8008"
  #     - "1883:1883"
  #     - "8000:8000"
  #     - "5672:5672"
  #     - "9000:9000"
  #     - "2222:2222"
  #   volumes:
  #     - type: tmpfs
  #       target: /dev/shm
  #       tmpfs:
  #         size: 2000000000 # 2G
  #     - type: volume
  #       source: solacedata
  #       target: /var/lib/solace
        
  postgres:
    image: postgres
    container_name: postgres
    # shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 = 128Mb
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres
  app:
    build:
      dockerfile: Dockerfile.vscode
    environment:
      - HTTP_PROXY=http://172.17.0.1:3128
      - HTTPS_PROXY=http://172.17.0.1:3128
    volumes:
      - type: bind
        source: /usr/local/share/ca-certificates
        target: /usr/local/share/ca-certificates
        read_only: true
      - ..:/go_gin_pgx_river_test:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  
volumes:
  solacedata:
  pgdata: